### PR TITLE
SE-43: Implement attachment upload

### PR DESCRIPTION
**Pull request by nhanbin03**
# What?
This PR involves implementing a method for frontend to upload attachments, and also modify the Attachment schema in MongoDB.

# Uploading attachments
The method used for attachment uploading is called a pre-signed URL. In this approach, the front end does not directly upload the file to the server but requests the server for a link to upload and then manually uploads the file to the link received.

The flow is as follows:
1. When the user uploads a file, the client requests the pre-signed URL through `/api/v1/servers/:serverId/channels/:channelId/messages/upload` using some file's metadata.
2. The server responds back with a `uploadUrl` and a `key`, which is later used for sending the message corresponding to the file.
3. The client sends a `PUT` request to the `uploadUrl` with the file attached.
4. When the client sends a `POST` request to `api/v1/servers/:serverId/channels/:channelId/messages`, it has to additionally specify the information of the attachments along with their keys.

# API Endpoints
## POST `/api/v1/servers/:serverId/channels/:channelId/messages/upload`
- **Description**: Request the pre-signed URL for upload a file
- **Request body**:
  - `filename` : the name of the file, including the file extension
  - `fileType` : the content-type of the file, for example, `application/pdf`
  - `fileSize` : the size of the file in the number of bytes.
- **Response body**:
  - `uploadUrl` : The URL to be uploaded to.
  - `key` : The key of the file, used to identify the file in the backend.

## _(Updated)_ POST `api/v1/servers/:serverId/channels/:channelId/messages`
- **Description**: Creates a new message within a channel.
- **New request body**:
```json
{
   ...
   "attachments": [
       {
            "filename": "The filename",
            "key": "The key received from the server when requesting for pre-signed URL"
       }
   ]
}
```

# Problems
1. The server cannot validate whether the file whose metadata is requested for the upload URL is the same as the file being uploaded to the pre-signed URL.
2. Because the server can only check the file size when it is requested for pre-signed URL, as a consequence of the first problem, the client may request for the pre-signed URL using false filesize, and then later upload large files to the pre-signed URL.

### CODE REVIEW

**Comment by ntploc21** [comment]
Hi @nhanbin03, for the uploaded file verification when uploading to Amazon S3, I suggest you could take a look at [@aws-sdk/s3-presigned-post](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-s3-presigned-post/). AWS S3 Presigned Post Data supports POST policy that I think could help you in verifying whether the uploaded file is valid. In your case, you could use `content-length-range` to check the file size (content length) and some other post policies to do another file check that can be found [here](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html#sigv4-PolicyConditions).

**Comment by nhanbin03** [comment]
# New:
The flow is updated as follows:
1. When the user uploads a file, the client requests the pre-signed URL through `/api/v1/servers/:serverId/channels/:channelId/messages/upload` using some file's metadata.
2. The server responds back with a `uploadUrl`, `fields`, and a `key`, which is later used for sending the message corresponding to the file.
3. The client sends a `POST` request to the `uploadUrl` with the file attached and the fields in `fields` as a FormData.
4. When the client sends a `POST` request to `api/v1/servers/:serverId/channels/:channelId/messages`, it has to additionally specify the information of the attachments along with their keys.

**Review by ntploc21 — APPROVED** [review]
Nice work!

**Review by ntploc21 — APPROVED** [review]
LGTM!

**Pull request merged**
